//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalipServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumuneDetay
    {
        public int id { get; set; }
        public string NumuneAdi { get; set; }
        public Nullable<int> UrunKodu { get; set; }
        public Nullable<int> KalipKodu { get; set; }
        public string Hammadde { get; set; }
        public string Renk { get; set; }
        public Nullable<short> KalipGozu { get; set; }
        public string KalipBoyutu { get; set; }
        public string BaskiSuresi { get; set; }
        public string TedarikciFirma { get; set; }
        public string CikanParcaMiktarı { get; set; }
        public string ParcaAgirligi { get; set; }
        public string ResimURL { get; set; }
    }
}
