//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalipServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numune
    {
        public int Id { get; set; }
        public string NumuneAdi { get; set; }
        public Nullable<int> UrunKodu { get; set; }
        public Nullable<int> KalipKodu { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
